# Generated by Django 5.2.8 on 2025-11-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouprequest',
            name='message',
        ),
    ]
